version: '3.1'
services:
  ic-webapp:
    container_name: ic-webapp
    image: hsocode/filrouge:latest
    ports:
      - 8080:8080
    environment:
      - ODOO_URL="http://192.168.56.3:80"
      - PGADMIN_URL=
    networks:
      - odoo_network
  postgres:
    environment:
      - POSTGRES_USER=hamadi
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    networks:
      - odoo_network
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    container_name: db_odoo
    image: 'postgres:10'
  odoo:
    depends_on:
      - postgres
    ports:
      - "80:8069"
    container_name: odoo
    networks:
      - odoo_network
    volumes:
      - '${PWD}/config:/etc/odoo'
      - '${PWD}/addons:/mnt/extra-addons'
      - 'odoo-web-data:/var/lib/odoo'
    environment:
      - USER=hamadi
      - PASSWORD=root
      - HOST=db_odoo
    image: odoo
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAUL_EMAIL=sow.hamadi@gmail.com
      - PGADMIN_DEFAUL_PASSWORD=admin1234
      - PGADMIN_LISTEN_PORT=80
    ports:
      - '5050:80'
    restart: always

    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - odoo_network
    #depend_on:
      #- postgres
volumes:
  odoo-web-data:
  pgdata:
  pgadmin:
networks:
  odoo_network:
